### ISSUE TITLE
example/trivial panic

### ISSUE THREAD

**Issue by extraymond** [geobacter-rs/geobacter#1]
Hi! When trying to run the trivial example. The following error was given:

```bash
thread 'grt-core-worker-9' panicked at 'called `Result::unwrap()` on an `Err` value: "read_option: expected 0 for None or 1 for Some"', src/librustc_metadata/rmeta/decoder.rs:226:9
```
---

**sys_info**

os: ubuntu 18.04 kernel 5.3
rocm: 3.3
rust used to compile geobacter: 1.44 stable
build_command: 
```cargo run --manifest-path rust-builder/Cargo.toml -- --target-dir ../geobacter-rust```

**Comment by DiamondLovesYou** [comment]
You have to set `RUSTFLAGS=-Z always-encode-mir -Z always-emit-metadata` so that the metadata is present for the runtime.

**Comment by extraymond** [comment]
Thanks it's working now!!!
