### ISSUE TITLE
What are the build requirements under windows?

### ISSUE THREAD

**Issue by apriori** [geobacter-rs/geobacter#8]
So far trying to build this with VS2019 build tools seems to fail horribly.

[fail_geobacter.txt](https://github.com/geobacter-rs/geobacter/files/6912808/fail_geobacter.txt)

**Comment by bjorn3** [comment]
```
E:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x86\msvcrt.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
```

It looks like you have installed an 32bit version of visual studio, but try to compile for 64bit. I don't think this is possible.

**Comment by apriori** [comment]
Hrm, this really happened. 
Additionally though, I had to install [WIX](https://wixtoolset.org/) and deactivate the building of the compiler docs. I assume there are path length issues. So this can be closed.
